Traceback (most recent call last):
  File "/Users/cerberus/miniconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/cerberus/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/cerberus/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/cerberus/miniconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/cerberus/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/cerberus/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/cerberus/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/cerberus/miniconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
peaks = ng.analysis.peakpick.pick(data_ref.real, pthres=0.1)
peaks
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/zy/7y6kpdbx6p1ffrp1vtxy3ttc0000gn/T/ipykernel_1403/1220298502.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mpeaks[0m [0;34m=[0m [0mng[0m[0;34m.[0m[0manalysis[0m[0;34m.[0m[0mpeakpick[0m[0;34m.[0m[0mpick[0m[0;34m([0m[0mdata_ref[0m[0;34m.[0m[0mreal[0m[0;34m,[0m [0mpthres[0m[0;34m=[0m[0;36m0.1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mpeaks[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/lib/python3.10/site-packages/nmrglue/analysis/peakpick.py[0m in [0;36mpick[0;34m(data, pthres, nthres, msep, algorithm, est_params, lineshapes, edge, diag, c_struc, c_ndil, cluster, table, axis_names)[0m
[1;32m    223[0m         [0mlocations[0m [0;34m=[0m [0madd_edge[0m[0;34m([0m[0mlocations[0m[0;34m,[0m [0medge[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    224[0m         [0;32mif[0m [0mtable[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 225[0;31m             [0;32mreturn[0m [0mpack_table[0m[0;34m([0m[0mlocations[0m[0;34m,[0m [0mcluster_ids[0m[0;34m,[0m [0mscales[0m[0;34m,[0m [0mamps[0m[0;34m,[0m [0maxis_names[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    226[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    227[0m             [0;32mreturn[0m [0mlocations[0m[0;34m,[0m [0mcluster_ids[0m[0;34m,[0m [0mscales[0m[0;34m,[0m [0mamps[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/lib/python3.10/site-packages/nmrglue/analysis/peakpick.py[0m in [0;36mpack_table[0;34m(locations, cluster_ids, scales, amps, axis_names)[0m
[1;32m    327[0m     [0manames[0m [0;34m=[0m [0maxis_names[0m[0;34m[[0m[0;34m-[0m[0mndim[0m[0;34m:[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    328[0m [0;34m[0m[0m
[0;32m--> 329[0;31m     [0mdt[0m [0;34m=[0m [0;34m[[0m[0;34m([0m[0ma[0m [0;34m+[0m [0;34m"_AXIS"[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mfloat[0m[0;34m)[0m [0;32mfor[0m [0ma[0m [0;32min[0m [0manames[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    330[0m     [0mrec[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mrec[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mlocations[0m[0;34m,[0m [0mdtype[0m[0;34m=[0m[0mdt[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    331[0m [0;34m[0m[0m

[0;32m~/miniconda3/lib/python3.10/site-packages/nmrglue/analysis/peakpick.py[0m in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m    327[0m     [0manames[0m [0;34m=[0m [0maxis_names[0m[0;34m[[0m[0;34m-[0m[0mndim[0m[0;34m:[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    328[0m [0;34m[0m[0m
[0;32m--> 329[0;31m     [0mdt[0m [0;34m=[0m [0;34m[[0m[0;34m([0m[0ma[0m [0;34m+[0m [0;34m"_AXIS"[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mfloat[0m[0;34m)[0m [0;32mfor[0m [0ma[0m [0;32min[0m [0manames[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    330[0m     [0mrec[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mrec[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mlocations[0m[0;34m,[0m [0mdtype[0m[0;34m=[0m[0mdt[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    331[0m [0;34m[0m[0m

[0;32m~/miniconda3/lib/python3.10/site-packages/numpy/__init__.py[0m in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    303[0m [0;34m[0m[0m
[1;32m    304[0m         [0;32mif[0m [0mattr[0m [0;32min[0m [0m__former_attrs__[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 305[0;31m             [0;32mraise[0m [0mAttributeError[0m[0;34m([0m[0m__former_attrs__[0m[0;34m[[0m[0mattr[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    306[0m [0;34m[0m[0m
[1;32m    307[0m         [0;31m# Importing Tester requires importing all of UnitTest which is not a[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

